### ISSUE TITLE
Select Bootstrap alternative framework

### ISSUE THREAD

**Issue by eeast** [eeast/GP1-FrontEndApplication#1]
Possible solutions on this page: https://hackr.io/blog/top-bootstrap-alternatives

**Comment by cmcnamara15** [comment]
Bulma seems like it might be a good one! Also found this framework which seems to be a solid choice for less experienced developers. https://materializecss.com/

**Comment by elizabetholsavsky** [comment]
I asked my tutor for his personal recommendations and he suggested materialize or tailwind. I will have to take a closer look at them both,

**Comment by eeast** [comment]
I actually used to use materialize back when I was teaching really basic javascript. It's been a while, but it's pretty easy, very similar to bootstrap and has great documentation.

**Comment by elizabetholsavsky** [comment]
It seems like a good middle ground between Bulma and Tailwind. Bulma was very simple and harder to customize, Tailwind while very customizable appears to take more time to learn.

**Comment by eeast** [comment]
Link to materialize.css: https://materializecss.com/

**Comment by HunterHester** [comment]
materialize.css: https://materializecss.com/ was what we decided 3/14

**Comment by HunterHester** [comment]
Reconsidering after demoing materialize, trying tailwind: https://tailwindcss.com/

**Comment by HunterHester** [comment]
Locked in MaterializeCSS
