### ISSUE TITLE
Search Results

### ISSUE THREAD

**Issue by rmessett15** [eeast/GP1-FrontEndApplication#10]
API call + parsing
** Building and displaying search results
--> leave box for trailer

Primary: Load top search result into the HMTL
Inputs: search string (request URL)
Outputs: HTML elements

Information to parse:

Poster
Title
Year
Runtime
Streaming services
Trailer link
Extra:

Cast
Director
IMDB link

Potential 2-person team: one on HMTL element creation, one on JSON parsing

**Comment by HunterHester** [comment]
TODO: Incorporate parsed data into HTML summary area. Mirror this layout:



![Image](https://user-images.githubusercontent.com/87347760/226507197-5c2958b0-c722-4c3f-93e6-e7b1201ec6c5.png)

**Comment by eeast** [comment]
Core functionality completed, additional work to be tracked elsewhere.
