### ISSUE TITLE
Aside (Favorites + Recent)

### ISSUE THREAD

**Issue by rmessett15** [eeast/GP1-FrontEndApplication#12]
Aside
** Recent searchs and favorites (localStorage)
--> in saving to local, include the API results

Primary: Favorites saved on top, recents below (possibly make scrollable)
Inputs: Each search string
Outputs: HTML buttons with embedded data related to search

**Comment by cmcnamara15** [comment]
Grateful for the collaboration of my teammates in getting this feature fully functioning.
