### ISSUE TITLE
Youtube API

### ISSUE THREAD

**Issue by rmessett15** [eeast/GP1-FrontEndApplication#13]
Adding youtube API to load trailer into box

Primary: Load youtube trailer into webpage
Inputs: youtube ID/youtube URL
Outputs: HMTL element/embedded video

**Comment by HunterHester** [comment]
YouTube API will be replaced with <iframe> elements inside HTML.

**Comment by eeast** [comment]
Abandoned API in favor of direct iframe injection.

**Comment by MisterBham** [comment]
used Youtube ID returned from streaming availability API. 
YouTube embed video working in modal
