### ISSUE TITLE
APIs to implement

### ISSUE THREAD

**Issue by rmessett15** [eeast/GP1-FrontEndApplication#4]
I heard from one of the TA's that we will be fetching data from APIs of our choosing for the first project, so I figured this could be the API issue where people can post their ideas.

**Comment by elizabetholsavsky** [comment]
Hey team! We will need to use at least 2 server side APIs for our project (as specified in BCS). Here is an extensive list of some free/public API's we might want to use. I will be looking through and thinking about how we can utilize the data in creative ways to solve a problem or serve some sort of purpose. I'll come back with some ideas later.

https://github.com/public-api-lists/public-api-lists

**Comment by HunterHester** [comment]
APIs:

[Streaming Availability API] https://www.movieofthenight.com/about/api
[YouTube API] https://developers.google.com/youtube/iframe_api_reference?csw=1
[BACKUP: METACRITIC] https://rapidapi.com/Prastiwar/api/metacriticapi
